[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions/dist"

[dev]
  targetPort = 4050
  functions = "netlify/functions/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
